#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct  8 16:54:47 2018

@author: JonahTuckman
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

#import the dataset
dataset = pd.read_csv("training.data", names = ['Sign'])
dataset[['Sign','Name']] = dataset["Sign"].str.split(" ", 1, expand=True)
X = dataset.iloc[: , 1:2].values
Y = dataset.iloc[: , 0:1].values
labelencoder_X = LabelEncoder()
X[: , 0] = labelencoder_X.fit_transform(X[: , 0])
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()
labelencoder_y = LabelEncoder()
Y = labelencoder_y.fit_transform(Y)

regressor = DecisionTreeRegressor()
regressor.fit(X, Y)

y_pred = regressor.predict(X)




